#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: Origen CoWork

# Short bio or description (displayed in the header)
description: Origen es un espacio de trabajo colaborativo flexible, con un café/bar diseñado para trabajar, sala multiusos para alquilar
ubicado en Araoz 1201, Palermo. Buenos Aires. Argentina.
# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: http://origencowork.com

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

# Author
author: Origen CoWork

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://raw.githubusercontent.com/origencowork/origencowork.github.io/master/assets/images/logo.jpeg
logo: https://raw.githubusercontent.com/origencowork/origencowork.github.io/master/assets/images/logo.jpeg

twitter:
  username: origencowork
facebook:
 publisher: origencowork
 admins:
   - https://www.facebook.com/christianbronstein14
   - https://www.facebook.com/gparrar
   - https://www.facebook.com/lermitrg

social:
  name: origencowork
  links:
    - https://twitter.com/origencowork
    - https://www.facebook.com/origencowork
    - https://www.linkedin.com/company/origen-cowork/
    - https://plus.google.com/100179707156619449236
    - https://github.com/origencowork

webmaster_verifications:
  google: E38KHsD6meQEA9Re26FKuTMGruMXlR51Zlz0DHNcJa8

lang: es_AR
#
# Flags below are optional
#

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email: origencowork@gmail.com
  facebook: origencowork
  flickr:
  github: origencowork/origencowork.github.io
  instagram: origencowork
  linkedin:
  pinterest:
  rss: # just type anything here for a working RSS icon
  twitter: origencowork
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: # channel/<your_long_string> or user/<user-name>
  googleplus: # anything in your profile username that comes after plus.google.com/


# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus:

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: UA-109678523-1
google_tag_manager: GTM-K2D7LLF

#
# !! You don't need to change any of the configuration flags below !!
#

# permalink: /:title/

# The release of Jekyll Now that you're using
version: v1.2.0

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# include pages
include: ['_pages']
# Use the following plug-ins
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
  - jekyll-maps

# Maps
maps:
    google:
      api_key: AIzaSyA01gWL5Unxo1lXI2-SeiEKa_BcGukDIKo

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md


#theme: jekyll-theme-cayman
